# Generated by Django 3.0.5 on 2020-06-11 22:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='edificio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'edificio',
                'verbose_name_plural': 'edificios',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='edificioTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('building_code', models.CharField(choices=[('PFE', 'PFE'), ('PFC', 'PFC'), ('PFU', 'PFU'), ('PFH', 'PFH'), ('PFP', 'PFP')], max_length=3, verbose_name='Building Code')),
                ('building_id', models.CharField(max_length=3, verbose_name='Building ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/edificios/', verbose_name='image')),
                ('building_name', models.CharField(help_text='Escribir el nombre del edificio', max_length=50, verbose_name='Building name')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('building_levels', models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='building_levels')),
                ('building_address', models.CharField(max_length=250, verbose_name='Building address')),
                ('building_ruc', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999999999999)])),
                ('building_accountant', models.CharField(max_length=20, verbose_name='Building Accountant ')),
                ('insurance_carrier', models.CharField(max_length=20, verbose_name='Building insurance carrier ')),
                ('administration_manager', models.CharField(max_length=20, verbose_name='administration manager name')),
                ('manager_administrator_name', models.CharField(max_length=50, verbose_name='Manager administrator name')),
                ('administrator_email', models.EmailField(max_length=254, verbose_name='administrator e-mail')),
                ('administrator_phonenumber', phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='administrator phonenumber')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='codigo')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='profit.edificio')),
            ],
            options={
                'verbose_name': 'edificio Translation',
                'db_table': 'profit_edificio_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
