# Generated by Django 3.0.5 on 2020-05-09 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('ProFixFWW', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='logo7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Logo Smart Quail'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='logo8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Logo de ProFix en barra de navegacion'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='logo9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Logo de ProFix blanco en pie de pagina'),
        ),
    ]
