# Generated by Django 3.0.5 on 2020-06-24 15:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='colegios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Instituciones Educativas',
                'verbose_name_plural': 'Institución Educativa',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Edificios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Información del Edificio',
                'verbose_name_plural': 'Datos del Edificio',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Instituciones Sanitarias',
                'verbose_name_plural': 'Institución Sanitaria',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Particulares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Instituciones Particulares',
                'verbose_name_plural': 'Institución Particular',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ParticularesTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('building_code', models.CharField(choices=[('PFE', 'PFE'), ('PFC', 'PFC'), ('PFU', 'PFU'), ('PFS', 'PFS'), ('PFP', 'PFP')], max_length=3, verbose_name='Building Code')),
                ('building_id', models.CharField(max_length=500, verbose_name='Building ID')),
                ('building_name', models.CharField(help_text='Escribir el nombre del edificio', max_length=50, verbose_name='Building name')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('buildings_levels', models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Buildings Numbers')),
                ('building_address', models.CharField(max_length=250, verbose_name='Building address')),
                ('building_ruc', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999999999999)])),
                ('building_accountant', models.CharField(max_length=20, verbose_name='Building Accountant ')),
                ('insurance_carrier', models.CharField(max_length=20, verbose_name='Building insurance carrier ')),
                ('administration_manager', models.CharField(max_length=20, verbose_name='administration manager name')),
                ('manager_administrator_name', models.CharField(max_length=50, verbose_name='Manager administrator name')),
                ('administrator_email', models.EmailField(max_length=254, verbose_name='administrator e-mail')),
                ('administrator_phonenumber', phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='administrator phonenumber')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='codigo')),
                ('project_number', models.CharField(blank=True, max_length=50, verbose_name='Projects Numbers')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='profixdatabase.Particulares')),
            ],
            options={
                'verbose_name': 'Instituciones Particulares Translation',
                'db_table': 'profixdatabase_particulares_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='hospitalTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('building_code', models.CharField(choices=[('PFE', 'PFE'), ('PFC', 'PFC'), ('PFU', 'PFU'), ('PFS', 'PFS'), ('PFP', 'PFP')], max_length=3, verbose_name='Building Code')),
                ('building_id', models.CharField(max_length=500, verbose_name='Building ID')),
                ('building_name', models.CharField(help_text='Escribir el nombre del edificio', max_length=50, verbose_name='Building name')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('buildings_levels', models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Buildings Numbers')),
                ('building_address', models.CharField(max_length=250, verbose_name='Building address')),
                ('building_ruc', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999999999999)])),
                ('building_accountant', models.CharField(max_length=20, verbose_name='Building Accountant ')),
                ('insurance_carrier', models.CharField(max_length=20, verbose_name='Building insurance carrier ')),
                ('administration_manager', models.CharField(max_length=20, verbose_name='administration manager name')),
                ('manager_administrator_name', models.CharField(max_length=50, verbose_name='Manager administrator name')),
                ('administrator_email', models.EmailField(max_length=254, verbose_name='administrator e-mail')),
                ('administrator_phonenumber', phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='administrator phonenumber')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='codigo')),
                ('project_number', models.CharField(blank=True, max_length=50, verbose_name='Projects Numbers')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='profixdatabase.hospital')),
            ],
            options={
                'verbose_name': 'Instituciones Sanitarias Translation',
                'db_table': 'profixdatabase_hospital_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EdificiosTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('building_code', models.CharField(choices=[('PFE', 'PFE'), ('PFC', 'PFC'), ('PFU', 'PFU'), ('PFS', 'PFS'), ('PFP', 'PFP')], max_length=3, verbose_name='Building Code')),
                ('building_id', models.CharField(max_length=500, verbose_name='Building ID')),
                ('building_name', models.CharField(help_text='Escribir el nombre del edificio', max_length=50, verbose_name='Building name')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('building_levels', models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(99)])),
                ('building_address', models.CharField(max_length=250, verbose_name='Building address')),
                ('building_ruc', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999999999999)])),
                ('building_accountant', models.CharField(max_length=20, verbose_name='Building Accountant ')),
                ('insurance_carrier', models.CharField(max_length=20, verbose_name='Building insurance carrier ')),
                ('administration_manager', models.CharField(max_length=20, verbose_name='administration manager name')),
                ('manager_administrator_name', models.CharField(max_length=50, verbose_name='Manager administrator name')),
                ('administrator_email', models.EmailField(max_length=254, verbose_name='administrator e-mail')),
                ('administrator_phonenumber', phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='administrator phonenumber')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='codigo')),
                ('project_number', models.CharField(blank=True, max_length=50, verbose_name='Projects Numbers')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='profixdatabase.Edificios')),
            ],
            options={
                'verbose_name': 'Información del Edificio Translation',
                'db_table': 'profixdatabase_edificios_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='colegiosTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('building_code', models.CharField(choices=[('PFE', 'PFE'), ('PFC', 'PFC'), ('PFU', 'PFU'), ('PFS', 'PFS'), ('PFP', 'PFP')], max_length=3, verbose_name='Building Code')),
                ('building_id', models.CharField(max_length=500, verbose_name='Building ID')),
                ('building_name', models.CharField(help_text='Escribir el nombre del edificio', max_length=50, verbose_name='Building name')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('buildings_levels', models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Buildings Numbers')),
                ('building_address', models.CharField(max_length=250, verbose_name='Building address')),
                ('building_ruc', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999999999999)])),
                ('building_accountant', models.CharField(max_length=20, verbose_name='Building Accountant ')),
                ('insurance_carrier', models.CharField(max_length=20, verbose_name='Building insurance carrier ')),
                ('administration_manager', models.CharField(max_length=20, verbose_name='administration manager name')),
                ('manager_administrator_name', models.CharField(max_length=50, verbose_name='Manager administrator name')),
                ('administrator_email', models.EmailField(max_length=254, verbose_name='administrator e-mail')),
                ('administrator_phonenumber', phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='administrator phonenumber')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='codigo')),
                ('project_number', models.CharField(blank=True, max_length=50, verbose_name='Projects Numbers')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='profixdatabase.colegios')),
            ],
            options={
                'verbose_name': 'Instituciones Educativas Translation',
                'db_table': 'profixdatabase_colegios_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
