# Generated by Django 3.0.5 on 2020-06-17 21:58

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProMain', '0001_translations'),
        ('profit', '0001_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Registro-Edificio',
                'verbose_name_plural': 'Registros-Edificios',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PlandeTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total', models.DateTimeField(null=True)),
                ('project2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items3', to='Project.Registro')),
            ],
            options={
                'verbose_name': 'Plan de Trabajo',
                'verbose_name_plural': 'Planes de Trabajo',
            },
        ),
        migrations.CreateModel(
            name='Analitycs2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True)),
                ('price2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ProTools Materials Price')),
                ('porce2', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='feed Protools Materials')),
                ('invoice_PM', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotipm2', to='ProMain.CotizacionPM')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items2', to='Project.Registro')),
            ],
            options={
                'verbose_name': 'Análisis de Costo Materiales',
                'verbose_name_plural': 'Análisis de Costos Materiales',
            },
        ),
        migrations.CreateModel(
            name='Analitycs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True)),
                ('price1', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Promain workhand Price')),
                ('porce', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='feed Promain WorkHand')),
                ('invoice_PM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotipm', to='ProMain.CotizacionPM')),
                ('projectPM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Project.Registro')),
            ],
            options={
                'verbose_name': 'Análisis de Costo Mano de Obra',
                'verbose_name_plural': 'Análisis de Costos Mano de Obra',
            },
        ),
        migrations.CreateModel(
            name='RegistroTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('project_code', models.CharField(choices=[('PRMC', 'PRMC'), ('PRMP', 'PRMP'), ('PRSE', 'PRSE'), ('PRSR', 'PRSR')], max_length=6, verbose_name='Project Code')),
                ('project_id', models.CharField(max_length=3, verbose_name='Project ID')),
                ('project_name', models.CharField(max_length=32, verbose_name='Project Name')),
                ('subject', models.TextField(verbose_name='Subject')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='codigo')),
                ('building_code2', models.ForeignKey(help_text='Escribir el Codigo del edificio', on_delete=django.db.models.deletion.CASCADE, to='profit.edificio')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='Project.Registro')),
            ],
            options={
                'verbose_name': 'Registro-Edificio Translation',
                'db_table': 'Project_registro_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
