# Generated by Django 3.0.5 on 2020-06-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analitycs',
            name='total2',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='analitycs2',
            name='total1',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
