# Generated by Django 3.0.5 on 2020-06-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_auto_20200617_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analitycs',
            name='total2',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='analitycs2',
            name='total1',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
