# Generated by Django 3.0.5 on 2020-06-22 15:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Diagnostico de Mantenimiento',
                'verbose_name_plural': 'Diagnostico de Mantenimiento',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Información del Edificio',
                'verbose_name_plural': 'Datos del Edificio',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=3, null=True, verbose_name='Codigo de Proyecto')),
                ('invoice_code', models.CharField(max_length=3, null=True, verbose_name='Codigo de Cotización')),
                ('created2', models.DateTimeField(null=True, verbose_name='Fecha de entrega de Proyecto')),
                ('porcet2', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Avance de Obra %')),
                ('porcet', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Porcetanje de Anticipo %')),
                ('value2', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor neto de la cotización')),
                ('value3', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('value4', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('building_code', models.CharField(choices=[('PFE', 'PFE'), ('PFC', 'PFC'), ('PFU', 'PFU'), ('PFH', 'PFH'), ('PFP', 'PFP')], max_length=3, verbose_name='Building Code')),
                ('building_id', models.CharField(max_length=3, verbose_name='Building ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/edificios/', verbose_name='image')),
                ('building_name', models.CharField(help_text='Escribir el nombre del edificio', max_length=50, verbose_name='Building name')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('building_levels', models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='building_levels')),
                ('building_address', models.CharField(max_length=250, verbose_name='Building address')),
                ('building_ruc', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999999999999)])),
                ('building_accountant', models.CharField(max_length=20, verbose_name='Building Accountant ')),
                ('insurance_carrier', models.CharField(max_length=20, verbose_name='Building insurance carrier ')),
                ('administration_manager', models.CharField(max_length=20, verbose_name='administration manager name')),
                ('manager_administrator_name', models.CharField(max_length=50, verbose_name='Manager administrator name')),
                ('administrator_email', models.EmailField(max_length=254, verbose_name='administrator e-mail')),
                ('administrator_phonenumber', phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='administrator phonenumber')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='codigo')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='Avadell.Perfil')),
            ],
            options={
                'verbose_name': 'Información del Edificio Translation',
                'db_table': 'Avadell_perfil_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DiagnosticoTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('report_code', models.CharField(choices=[('RMC', 'RMC'), ('RMP', 'RMP'), ('RSE', 'RSE'), ('RSR', 'RSR')], max_length=3, verbose_name='Report Code')),
                ('report_id', models.CharField(max_length=2, verbose_name='Report ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date report Created')),
                ('date_meet', models.DateTimeField(null=True, verbose_name='Date Technical meet')),
                ('project_name', models.CharField(help_text='Escribir Nombre de Proyecto', max_length=50, verbose_name='Project name')),
                ('item_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='item Name')),
                ('item_description', models.TextField(blank=True, null=True, verbose_name='Item description')),
                ('image_item', models.ImageField(blank=True, null=True, upload_to='static/edificios/', verbose_name='image Item')),
                ('item_name2', models.CharField(blank=True, max_length=20, null=True, verbose_name='item Name')),
                ('item_description2', models.TextField(blank=True, null=True, verbose_name='Item description')),
                ('image_item2', models.ImageField(blank=True, null=True, upload_to='static/edificios/', verbose_name='image Item')),
                ('item_name3', models.CharField(blank=True, max_length=20, null=True, verbose_name='item Name')),
                ('item_description3', models.TextField(blank=True, null=True, verbose_name='Item description')),
                ('image_item3', models.ImageField(blank=True, null=True, upload_to='static/edificios/', verbose_name='image Item')),
                ('promain_code', models.CharField(help_text='Codigo de Tecnico Profix Responsable', max_length=20, verbose_name='ProMain Code')),
                ('dayswork', models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(15)], verbose_name='Calendary days')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='codigo')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='Avadell.Diagnostico')),
            ],
            options={
                'verbose_name': 'Diagnostico de Mantenimiento Translation',
                'db_table': 'Avadell_diagnostico_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
