# Generated by Django 3.0.5 on 2020-06-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Avadell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectosAvadell',
            fields=[
            ],
            options={
                'verbose_name': 'Proyectos Avadell',
                'verbose_name_plural': 'Proyecto Avadell',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Avadell.proyecto',),
        ),
    ]
