# Generated by Django 3.0.5 on 2020-06-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avadell', '0003_auto_20200622_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='created2',
            field=models.DateField(null=True, verbose_name='Fecha de entrega de Proyecto'),
        ),
    ]
