# Generated by Django 3.0.5 on 2020-06-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Avadell', '0004_auto_20200622_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='created2',
            new_name='Fecha',
        ),
    ]
