# Generated by Django 3.0.5 on 2020-06-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avadell', '0005_auto_20200622_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Report_code', models.CharField(max_length=5, null=True, verbose_name='Codigo de Reporte')),
                ('invoice_type', models.CharField(choices=[('CMC', 'CMC'), ('CMP', 'CMP'), ('CSE', 'CSE'), ('CSR', 'CSR')], max_length=5, null=True, verbose_name='Tipo de Cotización')),
                ('invoice_id', models.CharField(max_length=5, null=True, verbose_name='ID de Cotización')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('item', models.CharField(max_length=200, null=True, verbose_name='Descripción Item-1')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Valor Unitario item-1')),
                ('item2', models.CharField(max_length=200, null=True, verbose_name='Descripción Item-2')),
                ('cost2', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Valor Unitario item-2')),
                ('item3', models.CharField(max_length=200, null=True, verbose_name='Descripción Item-3')),
                ('cost3', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Valor Unitario item-3')),
                ('item4', models.CharField(max_length=200, null=True, verbose_name='Descripción Item-4')),
                ('cost4', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Valor Unitario item-4')),
                ('iva', models.DecimalField(decimal_places=2, default=0.12, max_digits=5, verbose_name='I.V.A')),
                ('Total', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Valor Total')),
                ('term', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='codigo')),
            ],
        ),
    ]
