# Generated by Django 3.0.5 on 2020-06-22 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Avadell', '0006_cotizacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
    ]
