# Generated by Django 3.0.5 on 2020-06-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avadell', '0007_auto_20200622_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='item2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción Item-2'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='item3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción Item-3'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='item4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción Item-4'),
        ),
    ]
