# Generated by Django 3.0.5 on 2020-06-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avadell', '0008_auto_20200622_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='cost2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor Unitario item-2'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cost3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor Unitario item-3'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cost4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor Unitario item-4'),
        ),
    ]
