# Generated by Django 3.0.5 on 2020-06-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avadell', '0011_remove_cotizacion_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.12, max_digits=5, verbose_name='I.V.A'),
        ),
    ]
