# Generated by Django 3.0.5 on 2020-06-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avadell', '0012_cotizacion_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='sub',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Sub Total item 1'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='sub2',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Sub Total item 2'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='sub3',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Sub Total item 3'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='sub4',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Sub Total item 4'),
        ),
    ]
