# Generated by Django 3.0.5 on 2020-06-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avadell', '0013_auto_20200622_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='Total2',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Valor Final'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='Total',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Valor Total sin IVA'),
        ),
    ]
