# Generated by Django 3.0.5 on 2020-06-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avadell', '0014_auto_20200622_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiltranslation',
            name='building_id',
        ),
        migrations.AlterField(
            model_name='perfiltranslation',
            name='building_code',
            field=models.CharField(choices=[('PFE', 'PFE'), ('PFC', 'PFC'), ('PFU', 'PFU'), ('PFS', 'PFS'), ('PFP', 'PFP')], max_length=3, verbose_name='Building Code'),
        ),
    ]
