# Generated by Django 3.0.5 on 2020-06-24 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profixdatabase', '0001_initial'),
        ('Avadell', '0016_remove_perfiltranslation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiltranslation',
            name='building_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edificios', to='profixdatabase.Edificios'),
        ),
    ]
