# Generated by Django 3.0.5 on 2020-06-24 22:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profixprojects', '0003_auto_20200624_1237'),
        ('coupons', '0001_initial'),
        ('Avadell', '0017_auto_20200624_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='project_code',
            new_name='project_name',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='Total',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='Total2',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='canti',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='canti2',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='canti3',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='canti4',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='code',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='cost2',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='cost3',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='cost4',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='invoice_type',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='item2',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='item3',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='item4',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='sub2',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='sub3',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='sub4',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='term',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='coupons.Coupon'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='profixprojects.Project'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='report_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Avadell.Diagnostico'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Avadell.Cotizacion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_items', to='profixprojects.Project')),
            ],
        ),
    ]
