# Generated by Django 3.0.5 on 2020-06-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avadell', '0018_auto_20200624_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='Report_code',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='address',
            field=models.CharField(default=1, max_length=250, verbose_name='address'),
            preserve_default=False,
        ),
    ]
