# Generated by Django 3.0.5 on 2020-06-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Avadell', '0019_auto_20200624_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='invoice',
            new_name='cotizacion',
        ),
    ]
