# Generated by Django 3.0.5 on 2020-06-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='project_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Project Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='Building'),
        ),
    ]
