# Generated by Django 3.0.5 on 2020-06-17 15:09

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionPM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Cotizacion ProMain',
                'verbose_name_plural': 'Cotizaciones ProMain',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CotizacionPMTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('invoice_type', models.CharField(choices=[('PMMC', 'PMMC'), ('PMMP', 'PMMP'), ('PMSE', 'PMSE'), ('PMSR', 'PMSR')], max_length=6, verbose_name='Invoice Type')),
                ('invoice_id', models.CharField(max_length=3, verbose_name='Invoice ID')),
                ('project_name', models.CharField(max_length=32, verbose_name='Project Name')),
                ('subject', models.TextField(verbose_name='Subject')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='codigo')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='ProMain.CotizacionPM')),
            ],
            options={
                'verbose_name': 'Cotizacion ProMain Translation',
                'db_table': 'ProMain_cotizacionpm_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
