# Generated by Django 3.0.5 on 2020-06-24 16:43

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profixdatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Tipo de Mantenimiento',
                'verbose_name_plural': 'Tipo de Mantenimientos',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='main/%Y/%m/%d', verbose_name='Imagenes Reportadas')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitario')),
                ('available', models.BooleanField(default=True, verbose_name='Aprobado?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación de proyecto')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización de proyecto')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='profixprojects.mantenimiento', verbose_name='Categoría de Mantenimiento')),
            ],
            options={
                'verbose_name': 'Proyectos para Edificios',
                'verbose_name_plural': 'Proyecto para Edificio',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nombre de Proyecto')),
                ('slug', models.SlugField(max_length=200)),
                ('code2', models.CharField(blank=True, max_length=50, verbose_name='Codigo de Proyecto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción de Proyecto')),
                ('building_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edificio', to='profixdatabase.Edificios')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='profixprojects.Project')),
            ],
            options={
                'verbose_name': 'Proyectos para Edificios Translation',
                'db_table': 'profixprojects_project_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='mantenimientoTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(choices=[('Correctivo', 'PMC'), ('Preventivo', 'PMP'), ('Correctivo Sistema de Emergencia', 'PCSE'), ('Correctivo Sistema de Revestimientos', 'PCSR')], db_index=True, max_length=200, verbose_name='Tipo de Mantenimiento')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='profixprojects.mantenimiento')),
            ],
            options={
                'verbose_name': 'Tipo de Mantenimiento Translation',
                'db_table': 'profixprojects_mantenimiento_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
