# Generated by Django 3.0.5 on 2020-06-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profixprojects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttranslation',
            name='code2',
            field=models.CharField(blank=True, max_length=25, verbose_name='Codigo de Proyecto'),
        ),
    ]
