# Generated by Django 3.0.5 on 2020-06-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profixprojects', '0002_auto_20200624_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttranslation',
            name='code2',
            field=models.CharField(blank=True, max_length=500, verbose_name='Codigo de Proyecto'),
        ),
    ]
